apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipprovider
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ipprovider
  template:
    metadata:
      labels:
        app: ipprovider
    spec:
      containers:
      - name: ipprovider
        image: k41dockeruser/ipprovider
        ports:
        - containerPort: 8333
---
apiVersion: v1
kind: Service
metadata:
  name: ipprovider-service
spec:
  selector:
    app: ipprovider
  ports:
  - protocol: TCP
    port: 8033
    targetPort: 8333
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - name: greeter
        image: k41dockeruser/greeter
        ports:
        - containerPort: 8444
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-service
spec:
  selector:
    app: greeter
  ports:
  - protocol: TCP
    port: 8044
    targetPort: 8444
    nodePort: 31044
  type: NodePort